// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

uint256 constant MASK_256_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint248 constant MASK_248_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint240 constant MASK_240_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint232 constant MASK_232_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint224 constant MASK_224_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint216 constant MASK_216_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint208 constant MASK_208_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint200 constant MASK_200_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint192 constant MASK_192_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint184 constant MASK_184_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint176 constant MASK_176_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint168 constant MASK_168_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint160 constant MASK_160_BITS = 0x00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint152 constant MASK_152_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint144 constant MASK_144_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint136 constant MASK_136_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint128 constant MASK_128_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint120 constant MASK_120_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint112 constant MASK_112_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFFFF;

uint104 constant MASK_104_BITS = 0xFFFFFFFFFFFFFFFFFFFFFFFF;

uint96 constant MASK_96_BITS = 0xFFFFFFFFFFFFFFFFFFFFFF;

uint88 constant MASK_88_BITS = 0xFFFFFFFFFFFFFFFFFFFF;

uint80 constant MASK_80_BITS = 0xFFFFFFFFFFFFFFFFFF;

uint72 constant MASK_72_BITS = 0xFFFFFFFFFFFFFFFFFF;

uint64 constant MASK_64_BITS = 0xFFFFFFFFFFFFFFFF;

uint56 constant MASK_56_BITS = 0xFFFFFFFFFFFFFF;

uint48 constant MASK_48_BITS = 0xFFFFFFFFFFFF;

uint40 constant MASK_40_BITS = 0xFFFFFFFFFF;

uint32 constant MASK_32_BITS = 0xFFFFFFFF;

uint24 constant MASK_24_BITS = 0xFFFFFF;

uint16 constant MASK_16_BITS = 0xFFFF;

uint8 constant MASK_8_BITS = 0xFF;
